name: pc-dask
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=1.1.1
  - aiohttp=3.6.2
  - aioitertools=0.7.0
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - asciitree=0.3.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - atk=2.36.0
  - atk-1.0=2.36.0
  - attrs=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bleach=3.2.1
  - blosc=1.20.1
  - bokeh=2.2.1
  - botocore=1.17.44
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cachey=0.2.1
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - charls=2.1.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.1.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.20.0
  - dask-core=2.20.0
  - dask-glm=0.2.0
  - dask-labextension=3.0.0
  - dask-ml=1.7.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.20.0
  - docutils=0.15.2
  - entrypoints=0.3
  - fasteners=0.14.1
  - fastparquet=0.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.2
  - fribidi=1.0.10
  - fsspec=0.8.3
  - gdk-pixbuf=2.38.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.0
  - gobject-introspection=1.64.1
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gtk2=2.24.32
  - gts=0.7.6
  - h5py=2.10.0
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=67.1
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.16.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-server-proxy=1.5.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.8
  - jupyterlab_pygments=0.1.1
  - jupyterlab_server=1.2.0
  - jxrlib=1.1
  - kiwisolver=1.2.0
  - lcms2=2.11
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.1
  - libffi=3.2.1
  - libgfortran=4.0.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libllvm10=10.0.1
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libuv=1.39.0
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - libzopfli=1.0.3
  - llvm-openmp=10.0.1
  - llvmlite=0.34.0
  - locket=0.2.0
  - lxml=4.5.2
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mock=4.0.2
  - monotonic=1.5
  - msgpack-python=1.0.0
  - multidict=4.7.5
  - multipledispatch=0.6.0
  - nbclient=0.5.0
  - nbconvert=6.0.6
  - nbformat=5.0.7
  - ncurses=6.2
  - nest-asyncio=1.4.0
  - networkx=2.5
  - nodejs=14.12.0
  - notebook=6.1.4
  - numba=0.51.2
  - numcodecs=0.7.2
  - numexpr=2.7.1
  - numpy=1.19.1
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.2
  - pandas-datareader=0.8.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.7.1
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.3
  - pixman=0.38.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - psutil=5.7.2
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-graphviz=0.14.1
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - readline=8.0
  - requests=2.24.0
  - s3fs=0.5.1
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simpervisor=0.3
  - six=1.15.0
  - snakeviz=2.1.0
  - snappy=1.1.8
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - tblib=1.6.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - thrift=0.11.0
  - tifffile=2020.9.22
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.0.4
  - traitlets=5.0.4
  - typing_extensions=3.7.4.2
  - ujson=3.2.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.3.0
  - zarr=2.4.0
  - zeromq=4.3.2
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.2.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - kaggle==1.5.8
    - python-slugify==4.0.1
    - slugify==0.0.1
    - text-unidecode==1.3
    - tqdm==4.49.0
    - urllib3==1.24.3
